export const ROUTES = {
  HOME: "/",
  ABOUT: "/about",
  TERMS: "/terms",
  FAQ: "/faq",
  SUPPORT: "/support",
  DECKS: "/decks",
  MY_DECKS: "/decks/mine",
  DECK_CREATE: "/decks/create",
  DECK_DETAILS: (id) => `/decks/${id}`,
  DECK_EDIT: (id) => `/decks/${id}/edit`,
  DECK_CARD_MODE: (id) => `/decks/${id}/card-mode`,
  DECK_QUIZ_MODE: (id) => `/decks/${id}/quiz-mode`,
  USER_PROFILE: "/users/me",
  PROFILE: "/profile",
  RESET_PASSWORD: "/reset-password",
  BROWSE: "/browse",
  NOT_FOUND: "/not-found",
};
